### ISSUE TITLE
Cálculo simples nacional "progressivo"

### ISSUE THREAD

**Issue by RangelReale** [rpagliuca/calculadora-imposto-dev-remoto#6]
No cálculo do simples nacional, o cálculo está sendo feito "progressivamente", ou seja, na se o valor cai na faixa 3 por exemplo, é calculado a parte relativa a faixa 1 com o imposto da faixa 1, a proxima parte com o imposto da faixa 2, e assim por diante.

Mas não achei nenhum lugar falando que o cálculo funciona desse jeito, o que eu li que é se encontra a faixa e usa ela direto. Nesta página da contabilizei diz isso:
[https://www.contabilizei.com.br/contabilidade-online/calculo-simples-nacional/](https://www.contabilizei.com.br/contabilidade-online/calculo-simples-nacional/)

Voce leu em algum lugar que é assim que calcula, ou está sendo calculado errado?

**Comment by rpagliuca** [comment]
Fala, Rangel.

Na linha 122 do arquivo https://github.com/rpagliuca/calculadora-imposto-dev-remoto/blob/master/main/fiscal.go, onde estão declaradas as faixas do anexo 3, eu anotei um dos links que usei como fonte.

A fonte é essa: https://contabilizei.com.br/contabilidade-online/anexo-3-simples-nacional
Não foi a única que usei na época, mas foi a que escolhi referenciar ali por ser mais simples de entender.

Nesse link acima, você vê que tem uma coluna chamada VALOR A DEDUZIR (EM R$), que é exatamente um atalho para o cálculo progressivo.

Tem outros links também que mostram a utilização do valor a deduzir (cálculo progressivo), inclusive esse primeiro é da própria Receita:
* http://normas.receita.fazenda.gov.br/sijut2consulta/anexoOutros.action?idArquivoBinario=48432
* https://www.fenacor.org.br/noticias/simples-confira-aliquotas-e-valor-a-deduzir
* https://portaldacontabilidade.clmcontroller.com.br/como-calcular-o-simples-nacional/

Acho que a confusão se deu pois, como eu gostaria de ter a menor quantidade possível de informações hard-coded no programa, não armazenei diretamente o valor em R$ das parcelas a deduzir, pois são derivadas das próprias alíquotas das faixas anteriores do cálculo progressivo.

**Comment by RangelReale** [comment]
Ah entendi, esse é um conceito contábil que eu não sabia, a dedução é um atalho para chegar no mesmo lugar, obrigado pela explicação!
